version: '3'

services:
  monster:
    build: ./monster
    container_name: monster
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/admin/monsters/monsters:/etc/crazycow/monsters
    environment:
      TZ: 'Europe/Moscow'
      SERVER_PORT: 8081
      SPRING_BOOT_ADMIN_CLIENT_URL: 'http://admin:9999'
      MONSTERS_LOCATION: '/etc/crazycow/monsters'
    restart: always
  quote:
    build: ./quote
    container_name: quote
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: 'Europe/Moscow'
      SERVER_PORT: 8082
      SPRING_BOOT_ADMIN_CLIENT_URL: 'http://admin:9999'
    restart: always
  say:
    build: ./say
    container_name: say
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:8083
    environment:
      TZ: 'Europe/Moscow'
      SERVER_PORT: 8083
      MONSTER_URL: 'http://monster:8081/sayMessage'
      QUOTE_URL: 'http://quote:8082/getQuote'
      SPRING_BOOT_ADMIN_CLIENT_URL: 'http://admin:9999'
    restart: always
############### infrastructure ################
  admin:
    build: ./admin
    container_name: admin
    ports:
      - 9999:9999
    environment:
      TZ: 'Europe/Moscow'
      SPRING_PROFILES_ACTIVE: test
    restart: always
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9411:9411
    environment:
      SPRING_PROFILES_ACTIVE: test
    restart: always



