version: '3'

services:
  monster:
    image: sabbath666/monster
    container_name: monster
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SPRING_PROFILES_ACTIVE: test
    restart: always
  quote:
    image: sabbath666/quote
    container_name: quote
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SPRING_PROFILES_ACTIVE: test
    restart: always
  say:
    image: sabbath666/say
    container_name: say
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SPRING_PROFILES_ACTIVE: test
    restart: always
#################### infrastructure ###################
  consul:
    image: consul
    container_name: consul
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    command: "agent -server -ui -node=node-1 -bootstrap-expect=1 -client=0.0.0.0 -bind 192.168.75.75"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/prometheus:/etc/prometheus
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9090:9090
    restart: always

