server:
  port: 8081

spring:
  application:
    name: quote
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
