server:
  port: 8083

spring:
  application:
    name: say
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

quote.url: "http://localhost:8081/getQuote"
monster.url: "http://localhost:8082/sayMessage"