server:
  port: 8082

spring:
  application:
    name: monster
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

monsters.location: 'c:/etc/crazycow/monsters'
